### ISSUE TITLE
ErrorException: Undefined property: stdClass::$frequency

### ISSUE THREAD

**Issue by iPurpl3x** [ReFlar/StopForumSpam#15]
## Bug Report

**Current Behavior**
`ErrorException: Undefined property: stdClass::$frequency in /opt/flarum/vendor/fof/stopforumspam/src/StopForumSpam.php:116`

**Steps to Reproduce**
IDK

**Expected Behavior**
No error

**Environment**
- Flarum version: 1.0.4
- Extension version: 1.1.0
- PHP version: 8.0

**Comment by imorland** [comment]
Should be resolved by 74fcece57258910141904f877d3b21954ee4f722

**Comment by imorland** [comment]
Included in `1.1.1` release. Please re-open this issue if it persists after updating 👍
