### ISSUE TITLE
SFS server failure should be handled

### ISSUE THREAD

**Issue by franzliedke** [ReFlar/StopForumSpam#6]
We observed this on Discuss:

    GET https://www.stopforumspam.com/add.php?ip=X.X.X.X&email=XXX%40XXX&username=XXX&api_key=XXX` resulted in a `503 Service Unavailable` response:
    <p>IP Address cannot be added [CloudFlare]</p>

This should probably be caught by the `ReportSpammer` listener and either be ignored or result in an error message. (This is a temporary server problem on SFS' side.)

**Comment by dsevillamartin** [comment]
Done with f62913d10498ca04056b3b0fd6bf9be0f562629b.

FYI, this means the IP address that is being reported is one of CloudFlare's IPs.

When reporting local IP:
![image](https://user-images.githubusercontent.com/6401250/64997308-5399ac80-d8ae-11e9-8cd1-0dd6b0a7aaae.png)
